# Identity --------------------------------------------------------------------
substitutions:
  name: "sh_rgbw2_my_name"
  friendly_name: "Friendly name"
  ip: "192.168.5.x"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    # Kontor ÖV
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_kontor_ov
      hidden: true
    # Hall BV
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_hall_bv
      hidden: true
    # Garage
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_garage
      hidden: true
  
  manual_ip:
    static_ip: ${ip}
    gateway: 192.168.5.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback"
    password: !secret fallback_pw

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

#web_server:
#  port: 80

sensor:
  - platform: wifi_signal
    name: "${friendly_name} wifi signal"
    update_interval: 60s

light:
  - platform: rgbw
    name: bathroom_ledstrip_shelly_rgbw2
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
    effects:
      - random:
      - strobe:
      - flicker:

output:
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_r

  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    id: pwm_g

  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_b

  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: pwm_w