# Identity --------------------------------------------------------------------
substitutions:
  name: "sh_rgbw2_my_name"
  friendly_name: "Friendly name"
  ip: "192.168.5.x"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    # Kontor ÖV
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_kontor_ov
      hidden: true
    # Hall BV
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_hall_bv
      hidden: true
    # Garage
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_garage
      hidden: true
  
  manual_ip:
    static_ip: ${ip}
    gateway: 192.168.5.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback"
    password: !secret fallback_pw

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

#web_server:
#  port: 80

light:
  - platform: monochromatic
    name: ${device_name}_ch1
    id: ${device_name}_ch1
    output: ${device_name}_out_ch1
  - platform: monochromatic
    name: ${device_name}_ch2
    id: ${device_name}_ch2
    output: ${device_name}_out_ch2
  - platform: monochromatic
    name: ${device_name}_ch3
    id: ${device_name}_ch3
    output: ${device_name}_out_ch3
  - platform: monochromatic
    name: ${device_name}_ch4
    id: ${device_name}_ch4
    output: ${device_name}_out_ch4
# Example output entry
output:
  - platform: esp8266_pwm
    id: ${device_name}_out_ch1
    pin: GPIO12
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: ${device_name}_out_ch2
    pin: GPIO15
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: ${device_name}_out_ch3
    pin: GPIO14
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: ${device_name}_out_ch4
    pin: GPIO4
    frequency: 1000 Hz


binary_sensor:
  - platform: gpio
    pin: GPIO5
    id: light_0_touch
    on_click:
      then:
      - if:
            condition:
             - light.is_off: ${device_name}_ch1
             - light.is_off: ${device_name}_ch2
             - light.is_off: ${device_name}_ch3
             - light.is_off: ${device_name}_ch4
            then:
              - light.turn_on: 
                 id: ${device_name}_ch1
                 brightness: 1.0
              - light.turn_on: 
                 id: ${device_name}_ch2
                 brightness: 1.0
              - light.turn_on: 
                 id: ${device_name}_ch3
                 brightness: 1.0
              - light.turn_on: 
                 id: ${device_name}_ch4
                 brightness: 1.0
            else:
              - light.turn_off: ${device_name}_ch1
              - light.turn_off: ${device_name}_ch2
              - light.turn_off: ${device_name}_ch3
              - light.turn_off: ${device_name}_ch4
    on_press:
      then:
      - if:
          condition: 
            light.is_off: ${device_name}_ch1
          then:
          - delay: 0.5s
          - while:
              condition:
                binary_sensor.is_on: light_0_touch
              then:
                - light.dim_relative:
                    id: ${device_name}_ch1
                    relative_brightness: 5%
                    transition_length: 0.1s
                - delay: 0.1s
                - light.dim_relative:
                    id: ${device_name}_ch2
                    relative_brightness: 5%
                    transition_length: 0.1s
                - delay: 0.1s
                - light.dim_relative:
                    id: ${device_name}_ch3
                    relative_brightness: 5%
                    transition_length: 0.1s
                - delay: 0.1s
                - light.dim_relative:
                    id: ${device_name}_ch4
                    relative_brightness: 5%
                    transition_length: 0.1s
                - delay: 0.1s                
          else:
          - delay: 0.5s
          - while:
              condition:
                and:
                  - binary_sensor.is_on: light_0_touch
                  - light.is_on: ${device_name}_ch1
              then:
                - light.dim_relative:
                    id: ${device_name}_ch1
                    relative_brightness: -5%
                    transition_length: 0.1s
                - delay: 0.1s
                - light.dim_relative:
                    id: ${device_name}_ch2
                    relative_brightness: -5%
                    transition_length: 0.1s
                - delay: 0.1s
                - light.dim_relative:
                    id: ${device_name}_ch3
                    relative_brightness: -5%
                    transition_length: 0.1s
                - delay: 0.1s
                - light.dim_relative:
                    id: ${device_name}_ch4
                    relative_brightness: -5%
                    transition_length: 0.1s
                - delay: 0.1s   