# Identity --------------------------------------------------------------------
substitutions:
  name: "sh_1_my_name"
  friendly_name: "Friendly name"
  ip: "192.168.5.x"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

# Network ---------------------------------------------------------------------
wifi:
  networks:
    # Hall BV
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_hall_bv
      hidden: true
    # Kontor ÖV
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_kontor_ov
      hidden: true
    # Garage
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_garage
      hidden: true
  
  manual_ip:
    static_ip: ${ip}
    gateway: 192.168.5.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback"
    password: !secret fallback_pw

# Management ------------------------------------------------------------------
logger:

api:

ota:

# Device ----------------------------------------------------------------------
switch:
  - platform: gpio
    name: "${friendly_name}"
    icon: "mdi:lightbulb"
    pin: GPIO4
    id: relay

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  # Binary sensor for the button press
  - platform: gpio
    name: "${friendly_name} Input"
    pin:
      number: GPIO5
    on_press: # used with spring loaded switches
      - switch.toggle: relay
    #on_release: # used with spring loaded switches (inverted)
    #  - switch.turn_off: relay
    #on_state: # used with normal "toggle" switches
    #  - switch.toggle: relay

status_led:
  pin: GPIO0
