# Identity --------------------------------------------------------------------
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

# Network ---------------------------------------------------------------------
wifi:
  networks:
    - ssid: $wifi_ssid
      password: $wifi_password
      hidden: true
  
  manual_ip:
    static_ip: $wifi_ip
    gateway: $wifi_gateway
    subnet: $wifi_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback"
    password: $fallback_pw

# Management ------------------------------------------------------------------
logger:

api:

ota:

# Device ----------------------------------------------------------------------
switch:
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "${device_friendly_name}"
    icon: "mdi:lightbulb"
    pin: GPIO15
    id: relay
    
sensor:
  - platform: wifi_signal
    name: "${device_friendly_name} WiFi Signal"
    update_interval: 60s
    
  - platform: hlw8012
    cf_pin: GPIO05
    cf1_pin: GPIO13 # not used because it is not available on the 1PM but it is needed to compile
    sel_pin: GPIO14 # not used because it is not available on the 1PM but it is needed to compile
    power:
      name: "${device_friendly_name} Power"
      unit_of_measurement: W
      id: "Power"
      icon: mdi:flash-circle
      accuracy_decimals: 0
      filters:
      #Calibration needed for each device
      #Reading -> actual
      - calibrate_linear:
          - 0.49 -> 0.0
          - 377.0 -> 60.0
      - lambda: if (x <= 6.0) return 0; else return (x);
    update_interval: 10s
    
  # NTC Temperature
  - platform: ntc
    sensor: "Resistance"
    name: "${device_friendly_name} Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: "Resistance"
    sensor: "Source"
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: "Source"
    pin: A0
    update_interval: 10s

binary_sensor:
  - platform: status
    name: "${device_friendly_name} Status"
  # Binary sensor for the button press
  - platform: gpio
    name: "${device_friendly_name} Input"
    pin:
      number: GPIO4
    on_press: # used with spring loaded switches
      - switch.toggle: relay
    #on_release: # used with spring loaded switches (inverted)
    #  - switch.turn_off: relay
    #on_state: # used with normal "toggle" switches
    #  - switch.toggle: relay

status_led:
  pin: GPIO0
