# Substitutions ---------------------------------------------------------------
substitutions:
  # Higher value gives lower watt readout
  current_res: "0.000943"
  # Lower value gives lower voltage readout
  voltage_div: "2066"
  # measure a relatively strong load and enter values measured by the device vs the values your reference measurement provided here
  # power_cal_meas: "1700.0"
  # power_cal_real: "1700.0"

  max_current: "10"
  max_power: "2400"
  max_temp: "70.0"

# Identity --------------------------------------------------------------------
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

# Network ---------------------------------------------------------------------
wifi:
  networks:
    - ssid: $wifi_ssid
      password: $wifi_password
      hidden: true
  
  manual_ip:
    static_ip: $wifi_ip
    gateway: $wifi_gateway
    subnet: $wifi_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} FB"
    password: $fallback_pw
# Management ------------------------------------------------------------------
captive_portal:
logger:
api:
ota:
  platform: esphome

# Device ----------------------------------------------------------------------
time:
  - platform: sntp
    id: my_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: True
    name: "${device_friendly_name} Input"
    on_press:
      - switch.toggle: relay

status_led:
  pin:
    number: GPIO02
    inverted: True

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led

switch:
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO15
    id: relay
    name: "${device_friendly_name}"
    icon: mdi:power-socket-eu
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

sensor:
  - platform: wifi_signal
    name: "${device_friendly_name} WiFi Signal"
    update_interval: 60s

  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${device_friendly_name} Temp"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - switch.turn_off: relay
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${device_friendly_name}
              data_template:
                message: Switch turned off because temperature exceeded ${max_temp}°C

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm

  - platform: adc
    id: temp_analog_reading
    pin: A0

  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${device_friendly_name} Current"
      internal: true
      unit_of_measurement: "A"
      accuracy_decimals: 3
      icon: mdi:flash-circle
      on_value_range:
        - above: ${max_current}
          then:
            - switch.turn_off: relay
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${device_friendly_name}
                data_template:
                  message: Switch turned off because current exceeded ${max_current}A
    voltage:
      name: "${device_friendly_name} Voltage"
      internal: true
      unit_of_measurement: "V"
      icon: mdi:flash-circle
    power:
      name: "${device_friendly_name} Power"
      id: power
      unit_of_measurement: "W"
      icon: mdi:flash-circle
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: relay
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${device_friendly_name}
                data_template:
                  message: Switch turned off because power exceeded ${max_power}W
    update_interval: 10s

  - platform: total_daily_energy
    name: "${device_friendly_name} Daily Energy"
    power_id: power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh