substitutions:

  device_name: "YOUR DEVICE_NAME"
  device_friendly_name: "YOUR FRIENDLY NAME"
  wifi_ssid: "YOUR WIFI SSID"
  wifi_password: "YOUR WIFI PASSWORD"
  wifi_ip: "YOUR WIFI IP"
  wifi_gateway: "YOUR WIFI GATEWAY"
  wifi_subnet: "YOUR WIFI SUBNET"
  fallback_pw: "YOUR FALLBACK PASSWORD"

  # Only relevant for Shelly 2.5
  relay1_friendly_name: "YOUR FRIENDLY NAME"
  relay2_friendly_name: "YOUR FRIENDLY NAME"

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/4tbs/esptemplate
    ref: main
    # Uncomment the matching file
    # files: [shelly_1.yaml]
    # files: [shelly_1pm.yaml]
    # files: [shelly_25.yaml]
    # files: [shelly_plugs.yaml]
    # files: [shelly_rgbw2.yaml]
    refresh: 300s
