# Identity --------------------------------------------------------------------
substitutions:
  name: "sh_25_my_name"
  friendly_name: "Friendly name"
  name1: "Friendly name switch 1"
  name2: "Friendly name switch 1"
  ip: "192.168.5.x"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    # Hall BV
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_hall_bv
      hidden: true
    # Kontor ÖV
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_kontor_ov
      hidden: true
    # Garage
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_garage
      hidden: true
  
  manual_ip:
    static_ip: $(ip)
    gateway: 192.168.5.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback"
    password: !secret fallback_pw

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

#web_server:
#  port: 80

i2c:
  sda: GPIO12
  scl: GPIO14

switch:
  - platform: gpio
    name: "${friendly_name} ${name1}"
    icon: "mdi:lightbulb"
    pin: GPIO4
    id: relay1

  - platform: gpio
    name: "${friendly_name} ${name2}"
    icon: "mdi:lightbulb"
    pin: GPIO15
    id: relay2

sensor:
  - platform: wifi_signal
    name: "${friendly_name} wifi signal"
    update_interval: 60s
  - platform: ade7953
    voltage:
      name: "${friendly_name} Voltage"
      icon: mdi:flash-circle
    # Note! Shelly switches sensors for channel 1 & 2
    current_a:
      name: "${friendly_name} Current ${name2}"
      icon: mdi:flash-circle
      filters:
        - lambda: if (x <= 0.05) return 0; else return (x);
    current_b:
      name: "${friendly_name} Current ${name1}"
      icon: mdi:flash-circle
      filters:
        - lambda: if (x <= 0.05) return 0; else return (x);
    active_power_a:
      name: "${friendly_name} Power ${name2}"
      icon: mdi:flash-circle
      filters:
        - multiply: -1
        - lambda: if (x <= 6.0) return 0; else return (x);
    active_power_b:
      name: "${friendly_name} Power ${name1}"
      icon: mdi:flash-circle
      filters:
        - multiply: -1
        - lambda: if (x <= 6.0) return 0; else return (x);
    update_interval: 10s

  # NTC Temperature
  - platform: ntc
    sensor: ${name}_resistance_sensor
    name: "${friendly_name} Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: ${name}_resistance_sensor
    sensor: ${name}_source_sensor
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: ${name}_source_sensor
    pin: A0
    update_interval: 10s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
#      mode: INPUT_PULLUP
#      inverted: True
    name: "${friendly_name} Switch ${name1}"
    internal: true
    on_press:
      - switch.toggle: relay1
  - platform: gpio
    pin:
      number: GPIO5
#      mode: INPUT_PULLUP
#      inverted: True
    name: "${friendly_name} Switch ${name2}"
    internal: true
    on_press:
      - switch.toggle: relay2
  - platform: status
    name: "${friendly_name} Status"
    
#   GPIO16 added to lower temp in device
  - platform: gpio
    pin: GPIO16
    name: "ade7953 IRQ pin"
    internal: true

status_led:
  pin: GPIO0