# Identity --------------------------------------------------------------------
substitutions:
  name: "sh_1pm_my_name"
  friendly_name: "Friendly name"
  ip: "192.168.5.x"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

# Network ---------------------------------------------------------------------
wifi:
  networks:
    # Hall BV
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_hall_bv
      hidden: true
    # Kontor ÖV
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_kontor_ov
      hidden: true
    # Garage
    - ssid: !secret not_wlan_ssid
      password: !secret not_wlan_pw
      bssid: !secret wlan_bssid_garage
      hidden: true
  
  manual_ip:
    static_ip: $ip
    gateway: 192.168.5.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback"
    password: !secret fallback_pw

# Management ------------------------------------------------------------------
logger:

api:

ota:

# Device ----------------------------------------------------------------------
switch:
  - platform: gpio
    name: "${friendly_name}"
    icon: "mdi:lightbulb"
    pin: GPIO15
    id: relay
    
sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    
  - platform: hlw8012
    cf_pin: GPIO05
    cf1_pin: GPIO13 # not used because it is not available on the 1PM but it is needed to compile
    sel_pin: GPIO14 # not used because it is not available on the 1PM but it is needed to compile
    power:
      name: "${friendly_name} Power"
      unit_of_measurement: W
      id: "${name}_power"
      icon: mdi:flash-circle
      accuracy_decimals: 0
      filters:
      #Calibration needed for each device
      #Reading -> actual
      - calibrate_linear:
          - 0.49 -> 0.0
          - 377.0 -> 60.0
      - lambda: if (x <= 6.0) return 0; else return (x);
    update_interval: 10s
    
  # NTC Temperature
  - platform: ntc
    sensor: ${name}_resistance_sensor
    name: "${friendly_name} Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: ${name}_resistance_sensor
    sensor: ${name}_source_sensor
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: ${name}_source_sensor
    pin: A0
    update_interval: 10s

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  # Binary sensor for the button press
  - platform: gpio
    name: "${friendly_name} Input"
    pin:
      number: GPIO4
    on_press: # used with spring loaded switches
      - switch.toggle: relay
    #on_release: # used with spring loaded switches (inverted)
    #  - switch.turn_off: relay
    #on_state: # used with normal "toggle" switches
    #  - switch.toggle: relay

status_led:
  pin: GPIO0
