substitutions:

###### CHANGE ME START ######

  device_name: "YOUR DEVICE_NAME" 
  wifi_ssid: "YOUR WIFI SSID"
  wifi_password: "YOUR WIFI PASSWORD"
  wifi_ip: "YOUR WIFI IP"
  wifi_gateway: "YOUR WIFI GATEWAY"
  wifi_subnet: "YOUR WIFI SUBNET"
  fallback_pw: "YOUR FALLBACK PASSWORD"

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/4tbs/esptemplate
    ref: main
    files: [shelly_1pm.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
