# Identity --------------------------------------------------------------------
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

# Network ---------------------------------------------------------------------
wifi:
  networks:
    - ssid: $wifi_ssid
      password: $wifi_password
      hidden: true
  
  manual_ip:
    static_ip: $wifi_ip
    gateway: $wifi_gateway
    subnet: $wifi_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} FB"
    password: $fallback_pw

# Management ------------------------------------------------------------------
logger:
api:
ota:
  platform: esphome

# Device ----------------------------------------------------------------------
switch:
  - platform: gpio
    name: "${device_friendly_name}"
    icon: "mdi:lightbulb"
    pin: GPIO4
    id: relay

sensor:
  - platform: wifi_signal
    name: "${device_friendly_name} WiFi Signal"
    update_interval: 60s
    
binary_sensor:
  - platform: status
    name: "${device_friendly_name} Status"
  # Binary sensor for the button press
  - platform: gpio
    name: "${device_friendly_name} Input"
    pin:
      number: GPIO5
    on_press: # used with spring loaded switches
      - switch.toggle: relay
    #on_release: # used with spring loaded switches (inverted)
    #  - switch.turn_off: relay
    #on_state: # used with normal "toggle" switches
    #  - switch.toggle: relay

status_led:
  pin: GPIO0
